### ISSUE TITLE
CI failing due to FIAT changes

### ISSUE THREAD

**Issue by connorjward** [FInAT/FInAT#114] opened 2023-11-20 17:26 UTC
Two FInAT tests are [currently failing in CI](https://github.com/FInAT/FInAT/actions/runs/6933464251/job/18859666971?pr=113). I have tracked this down to a change somewhere in FIAT made in the last 2 weeks. Specifically I have validated that the tests pass using commit `f628a01efe9bcdc511ce8a91176756845d30add2` but do not with the latest `master`.

**Comment by pbrubeck** [comment] 2023-11-20 18:12
This issue is only showing up for Lagrange(interval, k), which recently got an update for its prime basis (we implemented the same Lagrange polynomial basis used for GL/GLL, and forgot to run the CI here). The issue is no longer present if we revert to the original Legendre basis. I'll see if it is possible to fix the issue while keeping the Lagrange polynomials.

**Comment by pbrubeck** [comment] 2023-11-20 18:28
We can understand what we are dealing with a bit better by looking at 
https://github.com/FInAT/FInAT/blob/40668275a85bea613828b5851a4c86f0a15700a3/finat/fiat_elements.py#L338-L341

There are no constant polynomials in the Lagrange basis, and we want to be able to simplify tabulations of cellwise constants.

**Comment by wence-** [comment] 2023-11-21 11:07
> There are no constant polynomials in the Lagrange basis, and we want to be able to simplify tabulations of cellwise constants.

That test is trying to check if the tabulation of the second derivative of a degree 1 or degree 2 polynomial is cellwise constant. Which I think it _is_. So is the problem that a simplification pass needs to run? There are a number of other places where tsfc does simplifications based on cellwise constant-ness (e.g. in computing jacobians for affine-mapped cells), have those also been defeated by this change?

**Comment by pbrubeck** [comment] 2023-11-21 16:25
I think you are right @wence-, this test should pass regardless of the choice of basis of the expansion set. Perhaps the problem is that `point_evaluation_ciarlet` might be trying to simplify constants in the derivatives of the expansion set (dmats) as opposed to doing this at the poly_set level?

**Comment by pbrubeck** [comment] 2023-11-21 16:30
>  There are a number of other places where tsfc does simplifications based on cellwise constant-ness (e.g. in computing jacobians for affine-mapped cells), have those also been defeated by this change?

At least in the past couple of years, since barycentric interpolation was introduced, if 1D coordinates lived in GLL (as opposed to Lagrange), we were not simplifying these affine Jacobians. 

Anyways, the moral here is that we should change most of our Lagrange tests to use GLL instead.

**Comment by wence-** [comment] 2023-11-21 16:53
> might be trying to simplify constants in the derivatives of the expansion set (dmats) as opposed to doing this at the poly_set level?

Almost all of finat works at the symbolic level. I can try and look at this at the weekend to see what the problem is. But perhaps you can just show what the table looks like when the test fails.

**Comment by pbrubeck** [comment] 2023-11-22 08:51
@wence- @connorjward I believe this issue wil be properly resolved with #115 and https://github.com/firedrakeproject/fiat/pull/54. I can confirm that these two branches are passing the firedrake and TSFC tests.

**Closed** 2023-11-22 16:51 UTC
