### ISSUE TITLE
MixedElement broken by recent UFL changes

### ISSUE THREAD

**Issue by angus-g** [FInAT/FInAT#145] opened 2024-11-20 22:59 UTC
From the changes introduced in #118, a lot of methods gained a `domain` parameter, but this hasn't been consistently applied. For example:

---

`domain` doesn't get passed through to `_check_component`
https://github.com/FInAT/FInAT/blob/d3a9b536233870d8853a6162c4112b07689fcdc1/finat/ufl/mixedelement.py#L138-L145

---

`MixedElement.extract_component` hasn't been changed at all
https://github.com/FInAT/FInAT/blob/d3a9b536233870d8853a6162c4112b07689fcdc1/finat/ufl/mixedelement.py#L175-L181

I think `TensorElement` probably has similar inconsistencies.

**Comment by angus-g** [comment] 2024-11-21 20:44
We have a call to `extract_subelement_component` to test for continuity of elements (https://github.com/g-adopt/g-adopt/blob/9827d7774e588cf315fa5c2c523da9618927733e/gadopt/utility.py#L154-L168) so absolutely none of our code runs on the latest Firedrake.

However, with the API change we'll also need to provide `domain` arguments anyway. There was also a TSFC issue that prevented us from updating our Firedrake version that was only merged yesterday too. Because of that, I had pinned our testing release of Firedrake. At some point it would be good to unpin, make the API changes and start following the latest version again.

**Comment by connorjward** [comment] 2024-12-06 13:47
Closing as we have moved FInAT into FIAT. The issue is now here: https://github.com/firedrakeproject/fiat/issues/105

**Closed by connorjward** 2024-12-06 13:47 UTC
